### ISSUE TITLE
How to do it?

### ISSUE THREAD

**Issue by botiapa** [gdude2002/Python-Plugin-Loader#14]
How can i use the `player.IsSprinting` method?

**Comment by gdude2002** [comment]
Wouldn't it be `player.isSprinting()`?

**Comment by botiapa** [comment]
yes but that does not work neither

**Comment by jomo** [comment]
can you provide some sample code that you think doesn't work?

**Comment by botiapa** [comment]
of course:

``` python
print "login.py STARTED"

@hook.enable
def onEnable():
    print "main.py enabled"

@hook.disable
def onDisable():
    print "main.py disabled"

@hook.event("player.PlayerJoinEvent", "normal")
def playerJoin(event):
    event.getPlayer().sendMessage("Hello from python")

@hook.command
def example(sender, command, label, args):
    sender.sendMessage("you just used command /example!")
    print "sender.IsSprinting()" 
```

**Comment by botiapa** [comment]
do i have to import something?

**Comment by gdude2002** [comment]
What do you mean by "It doesn't work"?

**Comment by botiapa** [comment]
I get an error here it is:

```
[20:13:59 INFO]: [PythonLoader] Loading Plugin login.py.dir
[20:14:06 WARN]: org.bukkit.plugin.InvalidPluginException: SyntaxError: ("mismatched input '' expecting DEDENT", ('<iostream>', 18, 1, '\tprint(sender.IsSprinting())\n'))
[20:14:06 WARN]:        at net.lahwran.bukkit.jython.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:290)
[20:14:06 WARN]:        at net.lahwran.bukkit.jython.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:111)
[20:14:06 WARN]:        at net.lahwran.bukkit.jython.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:81)
[20:14:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328)
[20:14:06 WARN]:        at com.master.bukkit.python.PythonLoader.onLoad(PythonLoader.java:86)
[20:14:06 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:299)
[20:14:06 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.<init>(CraftServer.java:256)
[20:14:06 WARN]:        at net.minecraft.server.v1_10_R1.PlayerList.<init>(PlayerList.java:70)
[20:14:06 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedPlayerList.<init>(SourceFile:14)
[20:14:06 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:183)
[20:14:06 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:517)
[20:14:06 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:14:06 WARN]: Caused by: SyntaxError: ("mismatched input '' expecting DEDENT", ('<iostream>', 18, 1, '\tprint(sender.IsSprinting())\n'))
[20:14:06 WARN]:        at org.python.core.ParserFacade.fixParseError(ParserFacade.java:95)
[20:14:06 WARN]:        at org.python.core.ParserFacade.parse(ParserFacade.java:190)
[20:14:06 WARN]:        at org.python.core.Py.compile_flags(Py.java:1956)
[20:14:06 WARN]:        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
[20:14:06 WARN]:        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
[20:14:06 WARN]:        at net.lahwran.bukkit.jython.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:238)
[20:14:06 WARN]:        ... 11 more
```

**Comment by jomo** [comment]
Well there's a syntax error in your code:

> ```
> SyntaxError: ("mismatched input '' expecting DEDENT", ('<iostream>', 18, 1, '\tprint(sender.IsSprinting())\n'))
> ```

Possibly mixing tabs & spaces?

**Comment by botiapa** [comment]
i don't think so check my code:

``` python
@hook.command
def example(sender, command, label, args):
sender.sendMessage("you just used command /example!")
print "sender.IsSprinting()" 
```

**Comment by gdude2002** [comment]
You really need to use proper code fences when pasting code.

Anyway, the syntax error you're getting is on the line containing `print(sender.IsSprinting())`, and there is indeed a tab before that line. Perhaps you meant to use four spaces?

**Comment by botiapa** [comment]
I think the problem is that i need to import something but i don't know how of where from

**Comment by botiapa** [comment]
No that is a tab

https://botiapa.gyazo.com/c9ee79fdb5498a53d8828fc914c4a749

**Comment by gdude2002** [comment]
You're not listening.

**Comment by botiapa** [comment]
oh sorry i did not get it i'm bad at english.I'll try it

**Comment by botiapa** [comment]
Thanks m8 its worked thank you again
